export   const months = [
    "All Year",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
  ];
export const years = ["2023"];
export  const keywordToCategoryMapping = {
    meny: "Dagligvare",
    narvesen: "Dagligvare",
    sammen: "Cafè",
    platou: "Sportsutstyr",
    "havn hjellestad": "Cafè",
    rema: "Dagligvare",
    coop: "Dagligvare",
    ica: "Dagligvare",
    bunnpris: "Dagligvare",
    kiwi: "Dagligvare",
    spar: "Dagligvare",
    felles: "Overføring til felleskonto",
    vipps: "Overføringer via Vipps",
    sport: "Sportsutstyr",
    gym: "Gym membership",
    outdoor: "Sportsutstyr",
    subscription: "Subscriptions",
    "redd barna": "Subscriptions",
    "apple.com": "Subscriptions",
    vinyl: "Spise/drikke ute",
    fjell: "Spise/drikke ute",
    skyss: "Kollektivtransport",
    "electronic arts": "Gaming",
    apotek: "Medisin",
    steam: "Gaming",
    zalando: "Klær",
    overføring: "Sparing ",
    kasse: "Lånekassen",
    valeri: "Spise/drikke ute",
    kino: "Kino",
    eleven: "Spise/drikke ute",
    dromedar: "cafè",
    fantofthallen: "Sportsutstyr",
    amazon: "Subscriptions",
    "coca-cola": "Spise/drikke ute",
    mcd: "Spise/drikke ute",
    faktura: "Faktura",
    tempo: "Spise/drikke ute",
    xxl: "Sportsutstyr",
    vinmonopolet: "Dagligvare",
    legal: "Spise/drikke ute",
    stereo: "Spise/drikke ute",
    zettle: "Spise/drikke ute",
    "may sawai": "Ferie",
    trevarefabrikken: "Ferie",
    travel: "Ferie",
    svolvaer: "Ferie",
    point: "Ferie",
    "avis rent": "Ferie",
    kebab: "Spise/drikke ute",
    elbil: "Bil",
    mobil: "Telefon",
    ahlens: "Klær",
    cafe: "Cafè",
    systembolaget: "Ferie",
    "a days march": "Klær",
    "recharge sweden": "Bil",
    shell: "Bil",
    "fra meg til noen": "Overføring fra noen via vipps",
    "til meg fra noen": "Overføring til noen via vipps",
    chili: "Telefon",
    "fredrik & l": "Dagligvare",
    "baker brun": "cafè",
    hotel: "Ferie",
    ferie: "Ferie",
    elkjoep: "Elektronikk",
    espresso: "cafè",
    "hjelle bakeren": "cafè",

  };

